# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Vn-0NxCW51Sj_9wXX6CqURCCXzpQwQXp
"""

import random
import plotly.express as px

"""In this part of code snippet we will generate the diffrent outcomes of rolling the dice over the provided number of times and subsequently add those values in a list and store them for further examnination."""

n =int(input("Enter the times you want to roll the dice:"))
dice= 6
results = []
for roll in range(n):
  out_put = random.randint(1,6)
  results.append(out_put)
print(results)

"""In this part of the code we are going to declare 2 list that will store the values of the sides we can get from a dice and also its frequency."""

frequencies =[]
dice_values=[]
for dice_value in range(1,7):
  dice_values.append(dice_value)
  frequency = results.count(dice_value)
  frequencies.append(frequency)
print(frequencies)

"""here we will use the 2 list created above for visualisation purpose where one list will take the position of x - axes and the other lsit as the y - axes"""

fig = px.bar(x= dice_values, y = frequencies)
fig.show()